"""add profile fields

Revision ID: 09766864b9fc
Revises: 0238d3c9173a
Create Date: 2026-01-22 19:50:21.917555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09766864b9fc'
down_revision = '0238d3c9173a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('bio')
        batch_op.drop_column('age')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
